//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace While_E.Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int userIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userRoleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int userID {
            get {
                return this.userIDField;
            }
            set {
                if ((this.userIDField.Equals(value) != true)) {
                    this.userIDField = value;
                    this.RaisePropertyChanged("userID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                if ((object.ReferenceEquals(this.userNameField, value) != true)) {
                    this.userNameField = value;
                    this.RaisePropertyChanged("userName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string userRole {
            get {
                return this.userRoleField;
            }
            set {
                if ((object.ReferenceEquals(this.userRoleField, value) != true)) {
                    this.userRoleField = value;
                    this.RaisePropertyChanged("userRole");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Task", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Task : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int taskIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string taskNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string taskDescField;
        
        private bool taskCompleteField;
        
        private int userIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int taskId {
            get {
                return this.taskIdField;
            }
            set {
                if ((this.taskIdField.Equals(value) != true)) {
                    this.taskIdField = value;
                    this.RaisePropertyChanged("taskId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string taskName {
            get {
                return this.taskNameField;
            }
            set {
                if ((object.ReferenceEquals(this.taskNameField, value) != true)) {
                    this.taskNameField = value;
                    this.RaisePropertyChanged("taskName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string taskDesc {
            get {
                return this.taskDescField;
            }
            set {
                if ((object.ReferenceEquals(this.taskDescField, value) != true)) {
                    this.taskDescField = value;
                    this.RaisePropertyChanged("taskDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool taskComplete {
            get {
                return this.taskCompleteField;
            }
            set {
                if ((this.taskCompleteField.Equals(value) != true)) {
                    this.taskCompleteField = value;
                    this.RaisePropertyChanged("taskComplete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int userID {
            get {
                return this.userIDField;
            }
            set {
                if ((this.userIDField.Equals(value) != true)) {
                    this.userIDField = value;
                    this.RaisePropertyChanged("userID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: http://tempuri.org/ ad alanındaki Get_UserResult öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_User", ReplyAction="*")]
        While_E.Service.Get_UserResponse Get_User(While_E.Service.Get_UserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_User", ReplyAction="*")]
        System.Threading.Tasks.Task<While_E.Service.Get_UserResponse> Get_UserAsync(While_E.Service.Get_UserRequest request);
        
        // CODEGEN: http://tempuri.org/ ad alanındaki name öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_User", ReplyAction="*")]
        While_E.Service.Add_UserResponse Add_User(While_E.Service.Add_UserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_User", ReplyAction="*")]
        System.Threading.Tasks.Task<While_E.Service.Add_UserResponse> Add_UserAsync(While_E.Service.Add_UserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Del_User", ReplyAction="*")]
        void Del_User(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Del_User", ReplyAction="*")]
        System.Threading.Tasks.Task Del_UserAsync(int ID);
        
        // CODEGEN: http://tempuri.org/ ad alanındaki name öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_User", ReplyAction="*")]
        While_E.Service.Update_UserResponse Update_User(While_E.Service.Update_UserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_User", ReplyAction="*")]
        System.Threading.Tasks.Task<While_E.Service.Update_UserResponse> Update_UserAsync(While_E.Service.Update_UserRequest request);
        
        // CODEGEN: http://tempuri.org/ ad alanındaki Get_TaskResult öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Task", ReplyAction="*")]
        While_E.Service.Get_TaskResponse Get_Task(While_E.Service.Get_TaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Task", ReplyAction="*")]
        System.Threading.Tasks.Task<While_E.Service.Get_TaskResponse> Get_TaskAsync(While_E.Service.Get_TaskRequest request);
        
        // CODEGEN: http://tempuri.org/ ad alanındaki name öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_Task", ReplyAction="*")]
        While_E.Service.Add_TaskResponse Add_Task(While_E.Service.Add_TaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add_Task", ReplyAction="*")]
        System.Threading.Tasks.Task<While_E.Service.Add_TaskResponse> Add_TaskAsync(While_E.Service.Add_TaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Del_Task", ReplyAction="*")]
        void Del_Task(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Del_Task", ReplyAction="*")]
        System.Threading.Tasks.Task Del_TaskAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_Task", ReplyAction="*")]
        void Update_Task(int ID, bool comp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_Task", ReplyAction="*")]
        System.Threading.Tasks.Task Update_TaskAsync(int ID, bool comp);
        
        // CODEGEN: http://tempuri.org/ ad alanındaki name öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Selected_User", ReplyAction="*")]
        While_E.Service.Get_Selected_UserResponse Get_Selected_User(While_E.Service.Get_Selected_UserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Selected_User", ReplyAction="*")]
        System.Threading.Tasks.Task<While_E.Service.Get_Selected_UserResponse> Get_Selected_UserAsync(While_E.Service.Get_Selected_UserRequest request);
        
        // CODEGEN: http://tempuri.org/ ad alanındaki Get_Selected_TaskResult öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Selected_Task", ReplyAction="*")]
        While_E.Service.Get_Selected_TaskResponse Get_Selected_Task(While_E.Service.Get_Selected_TaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Selected_Task", ReplyAction="*")]
        System.Threading.Tasks.Task<While_E.Service.Get_Selected_TaskResponse> Get_Selected_TaskAsync(While_E.Service.Get_Selected_TaskRequest request);
        
        // CODEGEN: http://tempuri.org/ ad alanındaki name öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_UserName", ReplyAction="*")]
        While_E.Service.Get_UserNameResponse Get_UserName(While_E.Service.Get_UserNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_UserName", ReplyAction="*")]
        System.Threading.Tasks.Task<While_E.Service.Get_UserNameResponse> Get_UserNameAsync(While_E.Service.Get_UserNameRequest request);
        
        // CODEGEN: http://tempuri.org/ ad alanındaki Get_CompTasksResult öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_CompTasks", ReplyAction="*")]
        While_E.Service.Get_CompTasksResponse Get_CompTasks(While_E.Service.Get_CompTasksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_CompTasks", ReplyAction="*")]
        System.Threading.Tasks.Task<While_E.Service.Get_CompTasksResponse> Get_CompTasksAsync(While_E.Service.Get_CompTasksRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_UserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_User", Namespace="http://tempuri.org/", Order=0)]
        public While_E.Service.Get_UserRequestBody Body;
        
        public Get_UserRequest() {
        }
        
        public Get_UserRequest(While_E.Service.Get_UserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Get_UserRequestBody {
        
        public Get_UserRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_UserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_UserResponse", Namespace="http://tempuri.org/", Order=0)]
        public While_E.Service.Get_UserResponseBody Body;
        
        public Get_UserResponse() {
        }
        
        public Get_UserResponse(While_E.Service.Get_UserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Get_UserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public While_E.Service.User[] Get_UserResult;
        
        public Get_UserResponseBody() {
        }
        
        public Get_UserResponseBody(While_E.Service.User[] Get_UserResult) {
            this.Get_UserResult = Get_UserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Add_UserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add_User", Namespace="http://tempuri.org/", Order=0)]
        public While_E.Service.Add_UserRequestBody Body;
        
        public Add_UserRequest() {
        }
        
        public Add_UserRequest(While_E.Service.Add_UserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Add_UserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string role;
        
        public Add_UserRequestBody() {
        }
        
        public Add_UserRequestBody(string name, string role) {
            this.name = name;
            this.role = role;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Add_UserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add_UserResponse", Namespace="http://tempuri.org/", Order=0)]
        public While_E.Service.Add_UserResponseBody Body;
        
        public Add_UserResponse() {
        }
        
        public Add_UserResponse(While_E.Service.Add_UserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Add_UserResponseBody {
        
        public Add_UserResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Update_UserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update_User", Namespace="http://tempuri.org/", Order=0)]
        public While_E.Service.Update_UserRequestBody Body;
        
        public Update_UserRequest() {
        }
        
        public Update_UserRequest(While_E.Service.Update_UserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Update_UserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string role;
        
        public Update_UserRequestBody() {
        }
        
        public Update_UserRequestBody(int ID, string name, string role) {
            this.ID = ID;
            this.name = name;
            this.role = role;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Update_UserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update_UserResponse", Namespace="http://tempuri.org/", Order=0)]
        public While_E.Service.Update_UserResponseBody Body;
        
        public Update_UserResponse() {
        }
        
        public Update_UserResponse(While_E.Service.Update_UserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Update_UserResponseBody {
        
        public Update_UserResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_TaskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_Task", Namespace="http://tempuri.org/", Order=0)]
        public While_E.Service.Get_TaskRequestBody Body;
        
        public Get_TaskRequest() {
        }
        
        public Get_TaskRequest(While_E.Service.Get_TaskRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Get_TaskRequestBody {
        
        public Get_TaskRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_TaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_TaskResponse", Namespace="http://tempuri.org/", Order=0)]
        public While_E.Service.Get_TaskResponseBody Body;
        
        public Get_TaskResponse() {
        }
        
        public Get_TaskResponse(While_E.Service.Get_TaskResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Get_TaskResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public While_E.Service.Task[] Get_TaskResult;
        
        public Get_TaskResponseBody() {
        }
        
        public Get_TaskResponseBody(While_E.Service.Task[] Get_TaskResult) {
            this.Get_TaskResult = Get_TaskResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Add_TaskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add_Task", Namespace="http://tempuri.org/", Order=0)]
        public While_E.Service.Add_TaskRequestBody Body;
        
        public Add_TaskRequest() {
        }
        
        public Add_TaskRequest(While_E.Service.Add_TaskRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Add_TaskRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string desc;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool comp;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int userID;
        
        public Add_TaskRequestBody() {
        }
        
        public Add_TaskRequestBody(string name, string desc, bool comp, int userID) {
            this.name = name;
            this.desc = desc;
            this.comp = comp;
            this.userID = userID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Add_TaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add_TaskResponse", Namespace="http://tempuri.org/", Order=0)]
        public While_E.Service.Add_TaskResponseBody Body;
        
        public Add_TaskResponse() {
        }
        
        public Add_TaskResponse(While_E.Service.Add_TaskResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Add_TaskResponseBody {
        
        public Add_TaskResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_Selected_UserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_Selected_User", Namespace="http://tempuri.org/", Order=0)]
        public While_E.Service.Get_Selected_UserRequestBody Body;
        
        public Get_Selected_UserRequest() {
        }
        
        public Get_Selected_UserRequest(While_E.Service.Get_Selected_UserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Get_Selected_UserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public Get_Selected_UserRequestBody() {
        }
        
        public Get_Selected_UserRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_Selected_UserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_Selected_UserResponse", Namespace="http://tempuri.org/", Order=0)]
        public While_E.Service.Get_Selected_UserResponseBody Body;
        
        public Get_Selected_UserResponse() {
        }
        
        public Get_Selected_UserResponse(While_E.Service.Get_Selected_UserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Get_Selected_UserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public While_E.Service.User[] Get_Selected_UserResult;
        
        public Get_Selected_UserResponseBody() {
        }
        
        public Get_Selected_UserResponseBody(While_E.Service.User[] Get_Selected_UserResult) {
            this.Get_Selected_UserResult = Get_Selected_UserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_Selected_TaskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_Selected_Task", Namespace="http://tempuri.org/", Order=0)]
        public While_E.Service.Get_Selected_TaskRequestBody Body;
        
        public Get_Selected_TaskRequest() {
        }
        
        public Get_Selected_TaskRequest(While_E.Service.Get_Selected_TaskRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Get_Selected_TaskRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ID;
        
        public Get_Selected_TaskRequestBody() {
        }
        
        public Get_Selected_TaskRequestBody(int ID) {
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_Selected_TaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_Selected_TaskResponse", Namespace="http://tempuri.org/", Order=0)]
        public While_E.Service.Get_Selected_TaskResponseBody Body;
        
        public Get_Selected_TaskResponse() {
        }
        
        public Get_Selected_TaskResponse(While_E.Service.Get_Selected_TaskResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Get_Selected_TaskResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public While_E.Service.Task[] Get_Selected_TaskResult;
        
        public Get_Selected_TaskResponseBody() {
        }
        
        public Get_Selected_TaskResponseBody(While_E.Service.Task[] Get_Selected_TaskResult) {
            this.Get_Selected_TaskResult = Get_Selected_TaskResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_UserNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_UserName", Namespace="http://tempuri.org/", Order=0)]
        public While_E.Service.Get_UserNameRequestBody Body;
        
        public Get_UserNameRequest() {
        }
        
        public Get_UserNameRequest(While_E.Service.Get_UserNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Get_UserNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public Get_UserNameRequestBody() {
        }
        
        public Get_UserNameRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_UserNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_UserNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public While_E.Service.Get_UserNameResponseBody Body;
        
        public Get_UserNameResponse() {
        }
        
        public Get_UserNameResponse(While_E.Service.Get_UserNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Get_UserNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public While_E.Service.User[] Get_UserNameResult;
        
        public Get_UserNameResponseBody() {
        }
        
        public Get_UserNameResponseBody(While_E.Service.User[] Get_UserNameResult) {
            this.Get_UserNameResult = Get_UserNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_CompTasksRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_CompTasks", Namespace="http://tempuri.org/", Order=0)]
        public While_E.Service.Get_CompTasksRequestBody Body;
        
        public Get_CompTasksRequest() {
        }
        
        public Get_CompTasksRequest(While_E.Service.Get_CompTasksRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Get_CompTasksRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ID;
        
        public Get_CompTasksRequestBody() {
        }
        
        public Get_CompTasksRequestBody(int ID) {
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get_CompTasksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get_CompTasksResponse", Namespace="http://tempuri.org/", Order=0)]
        public While_E.Service.Get_CompTasksResponseBody Body;
        
        public Get_CompTasksResponse() {
        }
        
        public Get_CompTasksResponse(While_E.Service.Get_CompTasksResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Get_CompTasksResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public While_E.Service.Task[] Get_CompTasksResult;
        
        public Get_CompTasksResponseBody() {
        }
        
        public Get_CompTasksResponseBody(While_E.Service.Task[] Get_CompTasksResult) {
            this.Get_CompTasksResult = Get_CompTasksResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : While_E.Service.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<While_E.Service.ServiceSoap>, While_E.Service.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        While_E.Service.Get_UserResponse While_E.Service.ServiceSoap.Get_User(While_E.Service.Get_UserRequest request) {
            return base.Channel.Get_User(request);
        }
        
        public While_E.Service.User[] Get_User() {
            While_E.Service.Get_UserRequest inValue = new While_E.Service.Get_UserRequest();
            inValue.Body = new While_E.Service.Get_UserRequestBody();
            While_E.Service.Get_UserResponse retVal = ((While_E.Service.ServiceSoap)(this)).Get_User(inValue);
            return retVal.Body.Get_UserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<While_E.Service.Get_UserResponse> While_E.Service.ServiceSoap.Get_UserAsync(While_E.Service.Get_UserRequest request) {
            return base.Channel.Get_UserAsync(request);
        }
        
        public System.Threading.Tasks.Task<While_E.Service.Get_UserResponse> Get_UserAsync() {
            While_E.Service.Get_UserRequest inValue = new While_E.Service.Get_UserRequest();
            inValue.Body = new While_E.Service.Get_UserRequestBody();
            return ((While_E.Service.ServiceSoap)(this)).Get_UserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        While_E.Service.Add_UserResponse While_E.Service.ServiceSoap.Add_User(While_E.Service.Add_UserRequest request) {
            return base.Channel.Add_User(request);
        }
        
        public void Add_User(string name, string role) {
            While_E.Service.Add_UserRequest inValue = new While_E.Service.Add_UserRequest();
            inValue.Body = new While_E.Service.Add_UserRequestBody();
            inValue.Body.name = name;
            inValue.Body.role = role;
            While_E.Service.Add_UserResponse retVal = ((While_E.Service.ServiceSoap)(this)).Add_User(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<While_E.Service.Add_UserResponse> While_E.Service.ServiceSoap.Add_UserAsync(While_E.Service.Add_UserRequest request) {
            return base.Channel.Add_UserAsync(request);
        }
        
        public System.Threading.Tasks.Task<While_E.Service.Add_UserResponse> Add_UserAsync(string name, string role) {
            While_E.Service.Add_UserRequest inValue = new While_E.Service.Add_UserRequest();
            inValue.Body = new While_E.Service.Add_UserRequestBody();
            inValue.Body.name = name;
            inValue.Body.role = role;
            return ((While_E.Service.ServiceSoap)(this)).Add_UserAsync(inValue);
        }
        
        public void Del_User(int ID) {
            base.Channel.Del_User(ID);
        }
        
        public System.Threading.Tasks.Task Del_UserAsync(int ID) {
            return base.Channel.Del_UserAsync(ID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        While_E.Service.Update_UserResponse While_E.Service.ServiceSoap.Update_User(While_E.Service.Update_UserRequest request) {
            return base.Channel.Update_User(request);
        }
        
        public void Update_User(int ID, string name, string role) {
            While_E.Service.Update_UserRequest inValue = new While_E.Service.Update_UserRequest();
            inValue.Body = new While_E.Service.Update_UserRequestBody();
            inValue.Body.ID = ID;
            inValue.Body.name = name;
            inValue.Body.role = role;
            While_E.Service.Update_UserResponse retVal = ((While_E.Service.ServiceSoap)(this)).Update_User(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<While_E.Service.Update_UserResponse> While_E.Service.ServiceSoap.Update_UserAsync(While_E.Service.Update_UserRequest request) {
            return base.Channel.Update_UserAsync(request);
        }
        
        public System.Threading.Tasks.Task<While_E.Service.Update_UserResponse> Update_UserAsync(int ID, string name, string role) {
            While_E.Service.Update_UserRequest inValue = new While_E.Service.Update_UserRequest();
            inValue.Body = new While_E.Service.Update_UserRequestBody();
            inValue.Body.ID = ID;
            inValue.Body.name = name;
            inValue.Body.role = role;
            return ((While_E.Service.ServiceSoap)(this)).Update_UserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        While_E.Service.Get_TaskResponse While_E.Service.ServiceSoap.Get_Task(While_E.Service.Get_TaskRequest request) {
            return base.Channel.Get_Task(request);
        }
        
        public While_E.Service.Task[] Get_Task() {
            While_E.Service.Get_TaskRequest inValue = new While_E.Service.Get_TaskRequest();
            inValue.Body = new While_E.Service.Get_TaskRequestBody();
            While_E.Service.Get_TaskResponse retVal = ((While_E.Service.ServiceSoap)(this)).Get_Task(inValue);
            return retVal.Body.Get_TaskResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<While_E.Service.Get_TaskResponse> While_E.Service.ServiceSoap.Get_TaskAsync(While_E.Service.Get_TaskRequest request) {
            return base.Channel.Get_TaskAsync(request);
        }
        
        public System.Threading.Tasks.Task<While_E.Service.Get_TaskResponse> Get_TaskAsync() {
            While_E.Service.Get_TaskRequest inValue = new While_E.Service.Get_TaskRequest();
            inValue.Body = new While_E.Service.Get_TaskRequestBody();
            return ((While_E.Service.ServiceSoap)(this)).Get_TaskAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        While_E.Service.Add_TaskResponse While_E.Service.ServiceSoap.Add_Task(While_E.Service.Add_TaskRequest request) {
            return base.Channel.Add_Task(request);
        }
        
        public void Add_Task(string name, string desc, bool comp, int userID) {
            While_E.Service.Add_TaskRequest inValue = new While_E.Service.Add_TaskRequest();
            inValue.Body = new While_E.Service.Add_TaskRequestBody();
            inValue.Body.name = name;
            inValue.Body.desc = desc;
            inValue.Body.comp = comp;
            inValue.Body.userID = userID;
            While_E.Service.Add_TaskResponse retVal = ((While_E.Service.ServiceSoap)(this)).Add_Task(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<While_E.Service.Add_TaskResponse> While_E.Service.ServiceSoap.Add_TaskAsync(While_E.Service.Add_TaskRequest request) {
            return base.Channel.Add_TaskAsync(request);
        }
        
        public System.Threading.Tasks.Task<While_E.Service.Add_TaskResponse> Add_TaskAsync(string name, string desc, bool comp, int userID) {
            While_E.Service.Add_TaskRequest inValue = new While_E.Service.Add_TaskRequest();
            inValue.Body = new While_E.Service.Add_TaskRequestBody();
            inValue.Body.name = name;
            inValue.Body.desc = desc;
            inValue.Body.comp = comp;
            inValue.Body.userID = userID;
            return ((While_E.Service.ServiceSoap)(this)).Add_TaskAsync(inValue);
        }
        
        public void Del_Task(int ID) {
            base.Channel.Del_Task(ID);
        }
        
        public System.Threading.Tasks.Task Del_TaskAsync(int ID) {
            return base.Channel.Del_TaskAsync(ID);
        }
        
        public void Update_Task(int ID, bool comp) {
            base.Channel.Update_Task(ID, comp);
        }
        
        public System.Threading.Tasks.Task Update_TaskAsync(int ID, bool comp) {
            return base.Channel.Update_TaskAsync(ID, comp);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        While_E.Service.Get_Selected_UserResponse While_E.Service.ServiceSoap.Get_Selected_User(While_E.Service.Get_Selected_UserRequest request) {
            return base.Channel.Get_Selected_User(request);
        }
        
        public While_E.Service.User[] Get_Selected_User(string name) {
            While_E.Service.Get_Selected_UserRequest inValue = new While_E.Service.Get_Selected_UserRequest();
            inValue.Body = new While_E.Service.Get_Selected_UserRequestBody();
            inValue.Body.name = name;
            While_E.Service.Get_Selected_UserResponse retVal = ((While_E.Service.ServiceSoap)(this)).Get_Selected_User(inValue);
            return retVal.Body.Get_Selected_UserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<While_E.Service.Get_Selected_UserResponse> While_E.Service.ServiceSoap.Get_Selected_UserAsync(While_E.Service.Get_Selected_UserRequest request) {
            return base.Channel.Get_Selected_UserAsync(request);
        }
        
        public System.Threading.Tasks.Task<While_E.Service.Get_Selected_UserResponse> Get_Selected_UserAsync(string name) {
            While_E.Service.Get_Selected_UserRequest inValue = new While_E.Service.Get_Selected_UserRequest();
            inValue.Body = new While_E.Service.Get_Selected_UserRequestBody();
            inValue.Body.name = name;
            return ((While_E.Service.ServiceSoap)(this)).Get_Selected_UserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        While_E.Service.Get_Selected_TaskResponse While_E.Service.ServiceSoap.Get_Selected_Task(While_E.Service.Get_Selected_TaskRequest request) {
            return base.Channel.Get_Selected_Task(request);
        }
        
        public While_E.Service.Task[] Get_Selected_Task(int ID) {
            While_E.Service.Get_Selected_TaskRequest inValue = new While_E.Service.Get_Selected_TaskRequest();
            inValue.Body = new While_E.Service.Get_Selected_TaskRequestBody();
            inValue.Body.ID = ID;
            While_E.Service.Get_Selected_TaskResponse retVal = ((While_E.Service.ServiceSoap)(this)).Get_Selected_Task(inValue);
            return retVal.Body.Get_Selected_TaskResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<While_E.Service.Get_Selected_TaskResponse> While_E.Service.ServiceSoap.Get_Selected_TaskAsync(While_E.Service.Get_Selected_TaskRequest request) {
            return base.Channel.Get_Selected_TaskAsync(request);
        }
        
        public System.Threading.Tasks.Task<While_E.Service.Get_Selected_TaskResponse> Get_Selected_TaskAsync(int ID) {
            While_E.Service.Get_Selected_TaskRequest inValue = new While_E.Service.Get_Selected_TaskRequest();
            inValue.Body = new While_E.Service.Get_Selected_TaskRequestBody();
            inValue.Body.ID = ID;
            return ((While_E.Service.ServiceSoap)(this)).Get_Selected_TaskAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        While_E.Service.Get_UserNameResponse While_E.Service.ServiceSoap.Get_UserName(While_E.Service.Get_UserNameRequest request) {
            return base.Channel.Get_UserName(request);
        }
        
        public While_E.Service.User[] Get_UserName(string name) {
            While_E.Service.Get_UserNameRequest inValue = new While_E.Service.Get_UserNameRequest();
            inValue.Body = new While_E.Service.Get_UserNameRequestBody();
            inValue.Body.name = name;
            While_E.Service.Get_UserNameResponse retVal = ((While_E.Service.ServiceSoap)(this)).Get_UserName(inValue);
            return retVal.Body.Get_UserNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<While_E.Service.Get_UserNameResponse> While_E.Service.ServiceSoap.Get_UserNameAsync(While_E.Service.Get_UserNameRequest request) {
            return base.Channel.Get_UserNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<While_E.Service.Get_UserNameResponse> Get_UserNameAsync(string name) {
            While_E.Service.Get_UserNameRequest inValue = new While_E.Service.Get_UserNameRequest();
            inValue.Body = new While_E.Service.Get_UserNameRequestBody();
            inValue.Body.name = name;
            return ((While_E.Service.ServiceSoap)(this)).Get_UserNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        While_E.Service.Get_CompTasksResponse While_E.Service.ServiceSoap.Get_CompTasks(While_E.Service.Get_CompTasksRequest request) {
            return base.Channel.Get_CompTasks(request);
        }
        
        public While_E.Service.Task[] Get_CompTasks(int ID) {
            While_E.Service.Get_CompTasksRequest inValue = new While_E.Service.Get_CompTasksRequest();
            inValue.Body = new While_E.Service.Get_CompTasksRequestBody();
            inValue.Body.ID = ID;
            While_E.Service.Get_CompTasksResponse retVal = ((While_E.Service.ServiceSoap)(this)).Get_CompTasks(inValue);
            return retVal.Body.Get_CompTasksResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<While_E.Service.Get_CompTasksResponse> While_E.Service.ServiceSoap.Get_CompTasksAsync(While_E.Service.Get_CompTasksRequest request) {
            return base.Channel.Get_CompTasksAsync(request);
        }
        
        public System.Threading.Tasks.Task<While_E.Service.Get_CompTasksResponse> Get_CompTasksAsync(int ID) {
            While_E.Service.Get_CompTasksRequest inValue = new While_E.Service.Get_CompTasksRequest();
            inValue.Body = new While_E.Service.Get_CompTasksRequestBody();
            inValue.Body.ID = ID;
            return ((While_E.Service.ServiceSoap)(this)).Get_CompTasksAsync(inValue);
        }
    }
}
